ALTER TABLE settings 
ADD COLUMN appLatestVersion VARCHAR(20) DEFAULT '1.0.0',
ADD COLUMN appBuildNumber INT DEFAULT 1,
ADD COLUMN appForceUpdate TINYINT(1) DEFAULT 0,
ADD COLUMN appLatestVersionIos VARCHAR(20) DEFAULT '1.0.0',
ADD COLUMN appBuildNumberIos INT DEFAULT 1,
ADD COLUMN appForceUpdateIos TINYINT(1) DEFAULT 0,
ADD COLUMN appDownloadUrlIos VARCHAR(255) DEFAULT '',
ADD COLUMN appUpdateMessage TEXT;
