ALTER TABLE settings ADD COLUMN `displayMode` TEXT;
ALTER TABLE settings ADD COLUMN `apiSource` TEXT;
ALTER TABLE settings ADD COLUMN `theme` TEXT;
ALTER TABLE settings ADD COLUMN `cmsVersion` TEXT;
ALTER TABLE settings ADD COLUMN `siteName` TEXT;
ALTER TABLE settings ADD COLUMN `seoTitle` TEXT;
ALTER TABLE settings ADD COLUMN `seoDesc` TEXT;
ALTER TABLE settings ADD COLUMN `seoKeywords` TEXT;
ALTER TABLE settings ADD COLUMN `seoAuthor` TEXT;
ALTER TABLE settings ADD COLUMN `seoPublisher` TEXT;
ALTER TABLE settings ADD COLUMN `themeColor` TEXT;
ALTER TABLE settings ADD COLUMN `canonicalBaseUrl` TEXT;
ALTER TABLE settings ADD COLUMN `ogTitle` TEXT;
ALTER TABLE settings ADD COLUMN `ogDesc` TEXT;
ALTER TABLE settings ADD COLUMN `ogType` TEXT;
ALTER TABLE settings ADD COLUMN `ogLocale` TEXT;
ALTER TABLE settings ADD COLUMN `verifyGoogle` TEXT;
ALTER TABLE settings ADD COLUMN `verifyBing` TEXT;
ALTER TABLE settings ADD COLUMN `verifyYandex` TEXT;
ALTER TABLE settings ADD COLUMN `customHead` TEXT;
ALTER TABLE settings ADD COLUMN `customBody` TEXT;
ALTER TABLE settings ADD COLUMN `logoUrl` TEXT;
ALTER TABLE settings ADD COLUMN `enableComics` INT DEFAULT 0;
ALTER TABLE settings ADD COLUMN `comicApiUrl` TEXT;
ALTER TABLE settings ADD COLUMN `tmdbApiKey` TEXT;
ALTER TABLE settings ADD COLUMN `cfTurnstileKey` TEXT;
ALTER TABLE settings ADD COLUMN `cfTurnstileSecret` TEXT;
ALTER TABLE settings ADD COLUMN `cfAnalyticsToken` TEXT;
ALTER TABLE settings ADD COLUMN `cfApiToken` TEXT;
ALTER TABLE settings ADD COLUMN `cfAccountId` TEXT;
ALTER TABLE settings ADD COLUMN `cfZoneId` TEXT;
ALTER TABLE settings ADD COLUMN `gaMeasurementId` TEXT;
ALTER TABLE settings ADD COLUMN `gaPropertyId` TEXT;
ALTER TABLE settings ADD COLUMN `googleIndexJson` TEXT;
ALTER TABLE settings ADD COLUMN `indexNowKey` TEXT;
ALTER TABLE settings ADD COLUMN `slugMovie` TEXT;
ALTER TABLE settings ADD COLUMN `slugWatch` TEXT;
ALTER TABLE settings ADD COLUMN `slugComic` TEXT;
ALTER TABLE settings ADD COLUMN `slugRead` TEXT;
ALTER TABLE settings ADD COLUMN `slugComicList` TEXT;
ALTER TABLE settings ADD COLUMN `slugList` TEXT;
ALTER TABLE settings ADD COLUMN `slugGenre` TEXT;
ALTER TABLE settings ADD COLUMN `slugCountry` TEXT;
ALTER TABLE settings ADD COLUMN `sitemapLimit` INT DEFAULT 5000;
ALTER TABLE settings ADD COLUMN `sitemapIncludeMovies` INT DEFAULT 1;
ALTER TABLE settings ADD COLUMN `sitemapIncludeCategories` INT DEFAULT 1;
ALTER TABLE settings ADD COLUMN `sitemapLinksPerFile` INT DEFAULT 1000;
ALTER TABLE settings ADD COLUMN `googleClientId` TEXT;
ALTER TABLE settings ADD COLUMN `googleClientSecret` TEXT;
ALTER TABLE settings ADD COLUMN `googleAllowedEmails` TEXT;
ALTER TABLE settings ADD COLUMN `msClientId` TEXT;
ALTER TABLE settings ADD COLUMN `msClientSecret` TEXT;
ALTER TABLE settings ADD COLUMN `msTenantId` TEXT;
ALTER TABLE settings ADD COLUMN `geminiApiKey` TEXT;
ALTER TABLE settings ADD COLUMN `openaiApiKey` TEXT;
ALTER TABLE settings ADD COLUMN `aiProvider` TEXT;
ALTER TABLE settings ADD COLUMN `allowAutoUpdate` INT DEFAULT 1;
ALTER TABLE settings ADD COLUMN `appApiKey` TEXT;
ALTER TABLE settings ADD COLUMN `appBannerEnabled` INT DEFAULT 0;
ALTER TABLE settings ADD COLUMN `appDownloadUrl` TEXT;
ALTER TABLE settings ADD COLUMN `appDownloadUrlTv` TEXT;
ALTER TABLE settings ADD COLUMN `appSchemaEnabled` INT DEFAULT 0;
ALTER TABLE settings ADD COLUMN `appSchemaName` TEXT;
ALTER TABLE settings ADD COLUMN `appSchemaOs` TEXT;
ALTER TABLE settings ADD COLUMN `appSchemaCategory` TEXT;
ALTER TABLE settings ADD COLUMN `appSchemaPrice` TEXT;
ALTER TABLE settings ADD COLUMN `appSchemaCurrency` TEXT;
ALTER TABLE settings ADD COLUMN `appSchemaRatingValue` TEXT;
ALTER TABLE settings ADD COLUMN `appSchemaRatingCount` TEXT;
ALTER TABLE settings ADD COLUMN `appLatestVersion` TEXT;
ALTER TABLE settings ADD COLUMN `appBuildNumber` INT DEFAULT 1;
ALTER TABLE settings ADD COLUMN `appForceUpdate` INT DEFAULT 0;
ALTER TABLE settings ADD COLUMN `appLatestVersionIos` TEXT;
ALTER TABLE settings ADD COLUMN `appBuildNumberIos` INT DEFAULT 1;
ALTER TABLE settings ADD COLUMN `appForceUpdateIos` INT DEFAULT 0;
ALTER TABLE settings ADD COLUMN `appDownloadUrlIos` TEXT;
ALTER TABLE settings ADD COLUMN `appUpdateMessage` TEXT;
ALTER TABLE settings ADD COLUMN `featuredType` TEXT;
ALTER TABLE settings ADD COLUMN `featuredMovieSlug` TEXT;
ALTER TABLE settings ADD COLUMN `featuredStyle` TEXT;
ALTER TABLE settings ADD COLUMN `featuredCount` INT DEFAULT 5;
ALTER TABLE settings ADD COLUMN `enableWatchingSession` INT DEFAULT 1;
ALTER TABLE settings ADD COLUMN `trackAnonymousSession` INT DEFAULT 0;
ALTER TABLE settings ADD COLUMN `footerText` TEXT;
ALTER TABLE settings ADD COLUMN `socialFacebook` TEXT;
ALTER TABLE settings ADD COLUMN `socialYoutube` TEXT;
ALTER TABLE settings ADD COLUMN `socialTwitter` TEXT;
ALTER TABLE settings ADD COLUMN `socialTelegram` TEXT;
ALTER TABLE settings ADD COLUMN `enableContinueWatching` INT DEFAULT 1;
ALTER TABLE settings ADD COLUMN `githubRepo` TEXT;
ALTER TABLE settings ADD COLUMN `githubBranch` TEXT;
ALTER TABLE settings ADD COLUMN `githubToken` TEXT;
ALTER TABLE settings ADD COLUMN `autoCheckUpdates` INT DEFAULT 1;
ALTER TABLE settings ADD COLUMN `updateServerUrl` TEXT;
ALTER TABLE settings ADD COLUMN `lastUpdateCheck` TEXT;
ALTER TABLE settings ADD COLUMN `latestRelease` TEXT;
