// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-xW6wy5jhth3rC38thJAuiZ2F8_pE9wY',
    appId: '1:606978027987:web:6d761888f614073621bf26',
    messagingSenderId: '606978027987',
    projectId: 'phimtop1-5d3e5',
    authDomain: 'phimtop1-5d3e5.firebaseapp.com',
    storageBucket: 'phimtop1-5d3e5.firebasestorage.app',
    measurementId: 'G-BSKGC0KVEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARj2j-oD5GGfNBGor9NKeDW-78nnCysQs',
    appId: '1:606978027987:android:52a1d9eaa3af423321bf26',
    messagingSenderId: '606978027987',
    projectId: 'phimtop1-5d3e5',
    storageBucket: 'phimtop1-5d3e5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX4o6_HE5Torjxm1ZsW5nXTY4knWmKxaA',
    appId: '1:606978027987:ios:4baad0a3894840ae21bf26',
    messagingSenderId: '606978027987',
    projectId: 'phimtop1-5d3e5',
    storageBucket: 'phimtop1-5d3e5.firebasestorage.app',
    androidClientId: '606978027987-hvo2lh16rn5h1o912c0mcbi3oqhki2ct.apps.googleusercontent.com',
    iosClientId: '606978027987-tu9ovkt4sppg0bk1ft4m41mc072lcu8e.apps.googleusercontent.com',
    iosBundleId: 'com.phimtop1.phimtop1Flutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX4o6_HE5Torjxm1ZsW5nXTY4knWmKxaA',
    appId: '1:606978027987:ios:4baad0a3894840ae21bf26',
    messagingSenderId: '606978027987',
    projectId: 'phimtop1-5d3e5',
    storageBucket: 'phimtop1-5d3e5.firebasestorage.app',
    androidClientId: '606978027987-hvo2lh16rn5h1o912c0mcbi3oqhki2ct.apps.googleusercontent.com',
    iosClientId: '606978027987-tu9ovkt4sppg0bk1ft4m41mc072lcu8e.apps.googleusercontent.com',
    iosBundleId: 'com.phimtop1.phimtop1Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-xW6wy5jhth3rC38thJAuiZ2F8_pE9wY',
    appId: '1:606978027987:web:f9e2695f86744c8021bf26',
    messagingSenderId: '606978027987',
    projectId: 'phimtop1-5d3e5',
    authDomain: 'phimtop1-5d3e5.firebaseapp.com',
    storageBucket: 'phimtop1-5d3e5.firebasestorage.app',
    measurementId: 'G-NXSS9PMR9P',
  );
}
